# Generated by Django 4.0.4 on 2022-08-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gadkille/images/')),
            ],
        ),
        migrations.CreateModel(
            name='BestClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('successfultours', models.PositiveIntegerField()),
                ('happytourist', models.PositiveIntegerField()),
                ('placeexplored', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='gadkille/images/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gadkille/images/')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gadkille/images/')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('subheading', models.CharField(max_length=150)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='gadkille/images/')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessfulTreks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('trekcount', models.IntegerField()),
                ('image', models.ImageField(upload_to='gadkille/images/')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingTreks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('rate', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField()),
                ('night', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='gadkille/images/')),
            ],
        ),
    ]
