# Generated by Django 4.0.4 on 2022-08-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadkille', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gadkille/images/')),
            ],
        ),
        migrations.AlterField(
            model_name='bestclick',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='designation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='homebackground',
            name='heading',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='homebackground',
            name='subheading',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='successfultreks',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='upcomingtreks',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='upcomingtreks',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
