# Generated by Django 4.0.4 on 2022-08-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadkille', '0002_aboutus_teammember_alter_bestclick_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('rate', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField()),
                ('night', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='gadkille/images/')),
            ],
        ),
    ]
