# Generated by Django 4.0.4 on 2022-08-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadkille', '0003_destination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebackground',
            options={'verbose_name': 'HomeBackground', 'verbose_name_plural': 'HomeBackgrounds'},
        ),
    ]
