# Generated by Django 4.0.4 on 2022-08-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadkille', '0004_alter_homebackground_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About US', 'verbose_name_plural': 'About US'},
        ),
        migrations.AlterModelOptions(
            name='homebackground',
            options={'verbose_name': 'Home Background', 'verbose_name_plural': 'Home Background'},
        ),
    ]
