# Generated by Django 4.0.4 on 2022-08-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadkille', '0005_alter_aboutus_options_alter_homebackground_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='successfultreks',
            options={'verbose_name': 'Successful Trek', 'verbose_name_plural': 'Successful Treks'},
        ),
    ]
