# Generated by Django 4.0.4 on 2022-08-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadkille', '0006_alter_successfultreks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contactno', models.PositiveBigIntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('no', models.PositiveBigIntegerField(max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Form',
                'verbose_name_plural': 'Contact Form',
            },
        ),
    ]
