# Generated by Django 4.0.4 on 2022-08-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadkille', '0007_contact_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactDetail',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='no',
            new_name='mobile',
        ),
    ]
