# Generated by Django 4.0.4 on 2022-08-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadkille', '0010_gallery_gallerybackground'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='upcomingtreks',
            options={'verbose_name': 'Upcoming Trek', 'verbose_name_plural': 'Upcoming Treks'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='height',
            field=models.CharField(choices=[('h-1', 'h-1'), ('h-2', 'h-2'), ('h-3', 'h-3'), ('h-4', 'h-4'), ('h-5', 'h-5'), ('h-6', 'h-6')], default='h-1', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='width',
            field=models.CharField(choices=[('w-1', 'w-1'), ('w-2', 'w-2'), ('w-3', 'w-3'), ('w-4', 'w-4'), ('w-5', 'w-5'), ('w-6', 'w-6')], default='w-1', max_length=5),
            preserve_default=False,
        ),
    ]
