# Generated by Django 4.0.4 on 2022-08-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadkille', '0011_alter_feedback_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='contactno',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='mobile',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='height',
            field=models.CharField(choices=[('h-2', 'h-2'), ('h-3', 'h-3'), ('h-4', 'h-4')], max_length=5),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='width',
            field=models.CharField(choices=[('w-1', 'w-1'), ('w-2', 'w-2'), ('w-3', 'w-3')], max_length=5),
        ),
    ]
