# Generated by Django 4.0.4 on 2022-09-02 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gadkille', '0012_alter_contactdetail_contactno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrekPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gadkille/images/')),
                ('location', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'TrekPhoto',
                'verbose_name_plural': 'TrekPhotos',
            },
        ),
        migrations.DeleteModel(
            name='ContactDetail',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='height',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='width',
        ),
        migrations.AddField(
            model_name='upcomingtreks',
            name='details',
            field=models.FileField(default=django.utils.timezone.now, upload_to='gadkille/images/'),
            preserve_default=False,
        ),
    ]
