# Generated by Django 4.0.4 on 2022-09-03 09:06

from django.db import migrations, models
import gadkille.models


class Migration(migrations.Migration):

    dependencies = [
        ('gadkille', '0015_alter_upcomingtreks_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutbackground',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_3MB]),
        ),
        migrations.AlterField(
            model_name='bestclick',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_2MB]),
        ),
        migrations.AlterField(
            model_name='homebackground',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_3MB]),
        ),
        migrations.AlterField(
            model_name='successfultreks',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_2MB]),
        ),
        migrations.AlterField(
            model_name='upcomingtreks',
            name='file',
            field=models.FileField(upload_to='gadkille/files/', validators=[gadkille.models.ValidateSize.validate_2MB]),
        ),
        migrations.AlterField(
            model_name='upcomingtreks',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_2MB]),
        ),
    ]
