# Generated by Django 4.0.4 on 2022-09-03 09:09

from django.db import migrations, models
import gadkille.models


class Migration(migrations.Migration):

    dependencies = [
        ('gadkille', '0016_alter_aboutbackground_image_alter_bestclick_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutbackground',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_1MB]),
        ),
    ]
