# Generated by Django 4.0.4 on 2022-09-04 18:57

from django.db import migrations, models
import gadkille.models


class Migration(migrations.Migration):

    dependencies = [
        ('gadkille', '0016_alter_aboutbackground_image_alter_bestclick_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuccessfulTreks',
            new_name='Activity',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='trekphoto',
            options={'verbose_name': 'Trek Photo', 'verbose_name_plural': 'Trek Photos'},
        ),
        migrations.RemoveField(
            model_name='upcomingtreks',
            name='location',
        ),
        migrations.AddField(
            model_name='upcomingtreks',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contactbackground',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_3MB]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_2MB]),
        ),
        migrations.AlterField(
            model_name='destinationbackground',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_3MB]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_2MB]),
        ),
        migrations.AlterField(
            model_name='gallerybackground',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_3MB]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_1MB]),
        ),
        migrations.AlterField(
            model_name='trekphoto',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_2MB]),
        ),
    ]
