# Generated by Django 4.0.4 on 2022-09-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadkille', '0017_rename_successfultreks_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingtreks',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
