# Generated by Django 4.0.4 on 2022-09-03 09:12

from django.db import migrations, models
import gadkille.models


class Migration(migrations.Migration):

    dependencies = [
        ('gadkille', '0017_alter_aboutbackground_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutbackground',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_3MB]),
        ),
        migrations.AlterField(
            model_name='contactbackground',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_3MB]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_2MB]),
        ),
        migrations.AlterField(
            model_name='destinationbackground',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_3MB]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_2MB]),
        ),
        migrations.AlterField(
            model_name='gallerybackground',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_3MB]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_1MB]),
        ),
        migrations.AlterField(
            model_name='trekphoto',
            name='image',
            field=models.ImageField(upload_to='gadkille/images/', validators=[gadkille.models.ValidateSize.validate_2MB]),
        ),
    ]
